# Sniperkit-Bot
# - Date: 2018-08-11 22:28:44.321147046 +0200 CEST m=+0.117332318
# - Status: analyzed

# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - freebsd
    - windows
    - darwin
    - linux
  goarch:
    - amd64
    - arm
    - arm64
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  # Reporitory to push the tap to.
  github:
    owner: jesseduffield
    name: homebrew-lazygit

  # Your app's homepage.
  # Default is empty.
  homepage: "https://github.com/sniperkit/snk.fork.lazygit/"

  # Your app's description.
  # Default is empty.
  description: "A simple terminal UI for git commands, written in Go"

  # # Packages your package depends on.
  # dependencies:
  #   - git
  #   - zsh

  # # Packages that conflict with your package.
  # conflicts:
  #   - svn
  #   - bash

# test comment to see if goreleaser only releases on new commits